#
# Copyright (c) 2025-2025 Ricardo do Canto
#
# This file is part of the EnduranceTrio Tracker project.
#
# Licensed under the Functional Software License (FSL), Version 1.1, ALv2 Future License
# (the "License");
#
# You may not use this file except in compliance with the License. You may obtain a copy
# of the License at https://fsl.software/
#
# THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF FITNESS FOR A PARTICULAR
# PURPOSE, MERCHANTABILITY, TITLE OR NON-INFRINGEMENT.
#
# IN NO EVENT WILL WE HAVE ANY LIABILITY TO YOU ARISING OUT OF OR RELATED TO THE
# SOFTWARE, INCLUDING INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES,
# EVEN IF WE HAVE BEEN INFORMED OF THEIR POSSIBILITY IN ADVANCE.
#

#
# Secrets Template
# ================
#
# This file serves as a template for the application-secrets.yaml file that needs to contain
# sensitive information such as database credentials.
#
# IMPORTANT SECURITY NOTES:
# - Copy this file to application-secrets.yaml and NEVER commit it to version control
# - The application-secrets.yaml file is excluded from version control to protect sensitive data
#   and should never be commited
#
# Usage Instructions:
# -------------------
# Step 1: Copy this template to create application-secrets.yaml, using the following command:
#         cp template-secrets.yaml application-secrets.yaml
#
# Step 2: Fill in all the placeholder values with the required values
#
# Step 3: Ensure that application-secrets.yaml is listed in your .gitignore file
#
spring:
  datasource:
    username: {USER}
    password: {PASSWORD}
